services:
  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - flappy
      - dino
      - mario
      - tetris
    restart: unless-stopped

  frontend:
    image: carlo005/webpage:latest
    container_name: game-selector
    expose:
      - "80"
    restart: unless-stopped

  flappy:
    image: carlo005/flappy:latest
    container_name: flappy-game
    expose:
      - "80"
    restart: unless-stopped

  dino:
    image: carlo005/dino:latest
    container_name: dino-game
    expose:
      - "80"
    restart: unless-stopped

  tetris:
    image: carlo005/tetris:latest
    container_name: tetris-game
    expose:
      - "80"
    restart: unless-stopped

  mario:
    image: carlo005/mario:latest
    container_name: mario-game
    expose:
      - "80"
    restart: unless-stopped
